appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: D073huPJQB4w5e6674yoR5PpqhbYTo9p1e3avpeb/zY2kpG5CV+4HeP8AchkhtAYyr9Zw+aL34SvzBmolW5QlNhd9K6MUqWv5e0UrxIqYWZ3mmeQ8iDav+rK1LaHwP7gqiMlnmkfKhuZHbn8MlxJ5Y8CxnD56pqhEaXZt+v53F+TCBrT7HCQfuCkLBpdMVuwv/AGPVLp0KakdcdhZnK6WZ9KhDyJH1kQzMBG1endV0AVd4tGw8HNJzrVvHoqdVzWQDFGm217pbwgVcEctDwSnxPmjs6GSWVgTAKD9joNtTpGSycoXCk1aJWJ9T87sxXiJP2IZw1kS5YCEgnhcDYXOlqoZ3iaIH/ZEGxLwWvVFxZoFVBt/4zAbnQAM/dJa6h8HLGMH23UneVwK2kkGx0F75zNXgjt+dnpwYFgWvW99yvADv97QlIyIbW/Ef5yQoSgEBT5x2djq48g/h3LZMF4abrMKm9lUKqzsymvu2nr/AwFQXGX52GHQdmBoQQH5jzu/vv3dVMjIimKTsLfwuKJgxeUbX8hcf4wU4C3yzrw9zoIozY8tAkdzPQJ6u3e0dJDgR8151hfGhuQ4gTE65+n+yJ0iqUM4sIDfD3lM1VyhZsGNd1ax3GnSgPjUNxdeU8RfGPH9hiMDbnqYT1XywLKeInbpLFkQIAfEK8aC8WzR6Y=}
